import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '@/context/authContext';

export const metadata: Metadata = {
  title: 'Nyawer App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full px-10 lg:px-14">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
